### ISSUE TITLE
Problems with power OFF / power demand

### ISSUE THREAD

**Issue by geraldFS** [philibertc/micronova_controller#22]
Hi there,

QA strikes again ;-)

Since the penultimate change to the source code, I have had the symptoms that I cannot switch off the oven if it has been running for a long time.
I can shift gears, but it continues to burn stubbornly.

The water temperature and room temperature are updated and are valid.
Only the switch on / off and the power requirement are frozen.

When I switch off the oven on the display, everything is updated and works again.

Regards
Gerald

**Comment by philibertc** [comment]
Hello, I will roll back to the previous commit, that new changes were
untested but I forgot to switch on dev branch.

**Comment by philibertc** [comment]
I revert the changes

**Comment by geraldFS** [comment]
Thanks!
Reacts again :-)

**Comment by geraldFS** [comment]
Hi there,

with the version dated December 4th, 2021 - the same phenomenon occurs again!

Switching on is possible
Switching off is not possible

Values are all displayed accordingly.

**Comment by philibertc** [comment]
Hello, that's strange...
I will inspect this soon.

**Comment by philibertc** [comment]
Hello, I reread the code, but I do not see anything that could influence the extinction. I will have to do some investigation.

**Comment by philibertc** [comment]
Hello, until I have more information about this problem, I will roll back to the previous functional version.

**Comment by philibertc** [comment]
Hello,
I'm going to make some simplifications in the program this weekend (especially in the web settings that I'm going to minimize to the wifi configuration until I know how to manage the rest better). This should make it easier to diagnose bugs like this one!

Best Regards,
Philibert

**Comment by philibertc** [comment]
Hello,
Can I close this issue?

Sincerely,
Philibert

**Comment by geraldFS** [comment]
Yes!
