### ISSUE TITLE
Why the use of the enable RX

### ISSUE THREAD

**Issue by netdata-be** [philibertc/micronova_controller#39]
I'm wondering why you choose to use a GPIO to enable the RX from the 1wire RS232?
I would be interested to know the reason behind this.

**Comment by philibertc** [comment]
Hello,
![image](https://user-images.githubusercontent.com/57588282/156791107-df76d8b9-5ae1-4870-b085-dae9982837f1.png)
If you don't use the "enable RX" the RX optocoupler (in the middle) will act as a pullup as soon as you try to use the TX (at the bottom) : when the TX pin is set to GND, the current can pass from the other side (from pin 4 to 3) to GND and in the process allow the current to pass through the optocoupler in the middle, which will act as a pullup. The Stove_Serial pin therefore never makes the low signal.
This is one of the problems of half-duplex serial (on a single cable).
I hope my explanation is clear,

Best Regards,
Philibert
