### ISSUE TITLE
MCZ Ego

### ISSUE THREAD

**Issue by ThomasTom86** [philibertc/micronova_controller#44]
Good morning,
 I came across your amount when I was looking to make my pellet stove smart.  Unfortunately, my oven (MCZ Ego Air 2017) does not have a CN 13 port installed.  Is it still somehow possible to integrate this model into the iobroker via mqtt?  There is an original Wifi module for this oven (unfortunately very expensive).  Thanks

https://youtu.be/yPMMZ5ETMB8

![image](https://user-images.githubusercontent.com/75570143/197373326-1a1b984f-266d-4cbc-9bf5-a0bf050a5f60.jpeg)

![image](https://user-images.githubusercontent.com/75570143/197373335-5b1acd90-210b-4d00-9fe8-ee79aad8d2bd.jpeg)

**Comment by jeanpolle** [comment]
If i had to guess; i'd say the 4 pins marked "com" are candidate for serial communication....

**Comment by philibertc** [comment]
Hello, 
According to the video, the "COM" pins seem to match. The use of only three cables also seems to confirm that it is the same protocol. You can make measurements with your multimeter by connecting the GND of the voltmeter to the 2nd from the left, then measuring the rest of the pins with the red probe.

Best Regards,
Philibert

**Comment by ThomasTom86** [comment]
Thank you for your message.  This is the measurement result from the Com port.

Best regards
Tom
![316F331B-3F0C-4282-AC31-DF1AA94FE00D](https://user-images.githubusercontent.com/75570143/198357693-edc4793e-3e56-4476-9382-23174999f882.jpeg)

**Comment by ThomasTom86** [comment]
I still found that
![Uploading E82E7FE0-994B-4061-98B0-E1E368BE3538.jpeg…]()

**Comment by ThomasTom86** [comment]
![25AB6115-BA87-4D07-91F5-26CC06F1A45F](https://user-images.githubusercontent.com/75570143/198709402-3e8dfe18-5f8d-4d3c-8b7e-7e68d6b7ff25.jpeg)
