### ISSUE TITLE
Use the 5V from the new micro serial output.

### ISSUE THREAD

**Issue by maxcalavera81** [philibertc/micronova_controller#56]
Hello @philibertc, what is the inconvenience of using the 5V output of the micro nova board to power your pcb and the wemos d1 mini?  So it would be possible to power everything without the need for external power.  I look forward to feedback, thank you very much for your attention...

**Comment by philibertc** [comment]
Hello, the problem is that I don't know the maximum power available on this 5V line, while the ~20V line is the main low voltage supply of the stove, so I prefer to use this one through a buck converter.
So this is just a precaution.

Best Regards,
Philibert
