### ISSUE TITLE
Arduino ide deepSleepInstant error

### ISSUE THREAD

**Issue by maxcalavera81** [philibertc/micronova_controller#59]
Hello, I'm having a "deepSleepInstant" error and I don't know how to solve it. Does anyone have any idea how or what I'm doing wrong?

![image](https://user-images.githubusercontent.com/43672635/214855016-aabedba8-400b-445f-b141-57d022b53b51.png)

**Comment by philibertc** [comment]
Hello, it seems that you have selected the esp32 version of the D1 mini, this program is made especially for the esp8266 version

**Comment by maxcalavera81** [comment]
@philibertc thank you very much, problem solved. It really was the poorly selected board. Thanks a lot for the project.

**Comment by philibertc** [comment]
Hello, I am glad to hear that. Could you please tell me the model of your stove if everything works well? You can make a pull request for this, and be listed among the contributors.

**Comment by maxcalavera81** [comment]
My stuva is a cadel crystal .  I'll do some more testing and then I'll give you feedback.
